FROM finchsec/kali
LABEL org.opencontainers.image.authors="thomas@finchsec.com"
RUN apt-get update && \
		apt-get install openssh-server --no-install-recommends -y && \
		apt-get autoclean && \
		rm -rf /var/lib/dpkg/status-old /var/lib/apt/lists/*
RUN useradd -ms /bin/bash kali && usermod --password kali kali
# SSH
RUN mkdir /run/sshd
EXPOSE 22
CMD [ "/usr/sbin/sshd", "-4", "-D" ]