FROM finchsec/kali
RUN apt update && \
		apt install openssh-server --no-install-recommends -y && \
		apt autoclean && \
		rm -rf /var/lib/dpkg/status-old /var/lib/apt/lists/*
RUN useradd -ms /bin/bash kali && usermod --password kali kali
# SSH
RUN mkdir /run/sshd
EXPOSE 22
CMD [ "/usr/sbin/sshd", "-4", "-D" ]